<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Enums\Status;
use App\Models\Country;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['name' => 'Afganistan', 'code' => 'AF'],
            ['name' => 'Arnavutluk', 'code' => 'AL'],
            ['name' => 'Cezayir', 'code' => 'DZ'],
            ['name' => 'Andorra', 'code' => 'AD'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Antigua ve Barbuda', 'code' => 'AG'],
            ['name' => 'Arjantin', 'code' => 'AR'],
            ['name' => 'Ermenistan', 'code' => 'AM'],
            ['name' => 'Avustralya', 'code' => 'AU'],
            ['name' => 'Avusturya', 'code' => 'AT'],
            ['name' => 'Azerbaycan', 'code' => 'AZ'],
            ['name' => 'Bahamalar', 'code' => 'BS'],
            ['name' => 'Bahreyn', 'code' => 'BH'],
            ['name' => 'Bangladeş', 'code' => 'BD'],
            ['name' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Belarus', 'code' => 'BY'],
            ['name' => 'Belçika', 'code' => 'BE'],
            ['name' => 'Belize', 'code' => 'BZ'],
            ['name' => 'Benin', 'code' => 'BJ'],
            ['name' => 'Butan', 'code' => 'BT'],
            ['name' => 'Bolivya', 'code' => 'BO'],
            ['name' => 'Bosna Hersek', 'code' => 'BA'],
            ['name' => 'Botsvana', 'code' => 'BW'],
            ['name' => 'Brezilya', 'code' => 'BR'],
            ['name' => 'Brunei', 'code' => 'BN'],
            ['name' => 'Bulgaristan', 'code' => 'BG'],
            ['name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Burundi', 'code' => 'BI'],
            ['name' => 'Kamboçya', 'code' => 'KH'],
            ['name' => 'Kamerun', 'code' => 'CM'],
            ['name' => 'Kanada', 'code' => 'CA'],
            ['name' => 'Yeşil Burun Adaları', 'code' => 'CV'],
            ['name' => 'Orta Afrika Cumhuriyeti', 'code' => 'CF'],
            ['name' => 'Çad', 'code' => 'TD'],
            ['name' => 'Şili', 'code' => 'CL'],
            ['name' => 'Çin', 'code' => 'CN'],
            ['name' => 'Kolombiya', 'code' => 'CO'],
            ['name' => 'Komorlar', 'code' => 'KM'],
            ['name' => 'Kongo', 'code' => 'CG'],
            ['name' => 'Kosta Rika', 'code' => 'CR'],
            ['name' => 'Hırvatistan', 'code' => 'HR'],
            ['name' => 'Küba', 'code' => 'CU'],
            ['name' => 'Kıbrıs', 'code' => 'CY'],
            ['name' => 'Çek Cumhuriyeti', 'code' => 'CZ'],
            ['name' => 'Danimarka', 'code' => 'DK'],
            ['name' => 'Cibuti', 'code' => 'DJ'],
            ['name' => 'Dominika', 'code' => 'DM'],
            ['name' => 'Dominik Cumhuriyeti', 'code' => 'DO'],
            ['name' => 'Ekvador', 'code' => 'EC'],
            ['name' => 'Mısır', 'code' => 'EG'],
            ['name' => 'El Salvador', 'code' => 'SV'],
            ['name' => 'Ekvator Ginesi', 'code' => 'GQ'],
            ['name' => 'Eritre', 'code' => 'ER'],
            ['name' => 'Estonya', 'code' => 'EE'],
            ['name' => 'Etiyopya', 'code' => 'ET'],
            ['name' => 'Fiji', 'code' => 'FJ'],
            ['name' => 'Finlandiya', 'code' => 'FI'],
            ['name' => 'Fransa', 'code' => 'FR'],
            ['name' => 'Gabon', 'code' => 'GA'],
            ['name' => 'Gambiya', 'code' => 'GM'],
            ['name' => 'Gürcistan', 'code' => 'GE'],
            ['name' => 'Almanya', 'code' => 'DE'],
            ['name' => 'Gana', 'code' => 'GH'],
            ['name' => 'Yunanistan', 'code' => 'GR'],
            ['name' => 'Grenada', 'code' => 'GD'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Gine', 'code' => 'GN'],
            ['name' => 'Gine-Bissau', 'code' => 'GW'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Haiti', 'code' => 'HT'],
            ['name' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Macaristan', 'code' => 'HU'],
            ['name' => 'İzlanda', 'code' => 'IS'],
            ['name' => 'Hindistan', 'code' => 'IN'],
            ['name' => 'Endonezya', 'code' => 'ID'],
            ['name' => 'İran', 'code' => 'IR'],
            ['name' => 'Irak', 'code' => 'IQ'],
            ['name' => 'İrlanda', 'code' => 'IE'],
            ['name' => 'İsrail', 'code' => 'IL'],
            ['name' => 'İtalya', 'code' => 'IT'],
            ['name' => 'Jamaika', 'code' => 'JM'],
            ['name' => 'Japonya', 'code' => 'JP'],
            ['name' => 'Ürdün', 'code' => 'JO'],
            ['name' => 'Kazakistan', 'code' => 'KZ'],
            ['name' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Kiribati', 'code' => 'KI'],
            ['name' => 'Kuzey Kore', 'code' => 'KP'],
            ['name' => 'Güney Kore', 'code' => 'KR'],
            ['name' => 'Kuveyt', 'code' => 'KW'],
            ['name' => 'Kırgızistan', 'code' => 'KG'],
            ['name' => 'Laos', 'code' => 'LA'],
            ['name' => 'Letonya', 'code' => 'LV'],
            ['name' => 'Lübnan', 'code' => 'LB'],
            ['name' => 'Lesotho', 'code' => 'LS'],
            ['name' => 'Liberya', 'code' => 'LR'],
            ['name' => 'Libya', 'code' => 'LY'],
            ['name' => 'Lihtenştayn', 'code' => 'LI'],
            ['name' => 'Litvanya', 'code' => 'LT'],
            ['name' => 'Lüksemburg', 'code' => 'LU'],
            ['name' => 'Madagaskar', 'code' => 'MG'],
            ['name' => 'Malavi', 'code' => 'MW'],
            ['name' => 'Malezya', 'code' => 'MY'],
            ['name' => 'Maldivler', 'code' => 'MV'],
            ['name' => 'Mali', 'code' => 'ML'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Moritanya', 'code' => 'MR'],
            ['name' => 'Mauritius', 'code' => 'MU'],
            ['name' => 'Meksika', 'code' => 'MX'],
            ['name' => 'Moldova', 'code' => 'MD'],
            ['name' => 'Monako', 'code' => 'MC'],
            ['name' => 'Moğolistan', 'code' => 'MN'],
            ['name' => 'Karadağ', 'code' => 'ME'],
            ['name' => 'Fas', 'code' => 'MA'],
            ['name' => 'Mozambik', 'code' => 'MZ'],
            ['name' => 'Myanmar', 'code' => 'MM'],
            ['name' => 'Namibya', 'code' => 'NA'],
            ['name' => 'Nauru', 'code' => 'NR'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Hollanda', 'code' => 'NL'],
            ['name' => 'Yeni Zelanda', 'code' => 'NZ'],
            ['name' => 'Nikaragua', 'code' => 'NI'],
            ['name' => 'Nijer', 'code' => 'NE'],
            ['name' => 'Nijerya', 'code' => 'NG'],
            ['name' => 'Norveç', 'code' => 'NO'],
            ['name' => 'Umman', 'code' => 'OM'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Palau', 'code' => 'PW'],
            ['name' => 'Panama', 'code' => 'PA'],
            ['name' => 'Papua Yeni Gine', 'code' => 'PG'],
            ['name' => 'Paraguay', 'code' => 'PY'],
            ['name' => 'Peru', 'code' => 'PE'],
            ['name' => 'Filipinler', 'code' => 'PH'],
            ['name' => 'Polonya', 'code' => 'PL'],
            ['name' => 'Portekiz', 'code' => 'PT'],
            ['name' => 'Katar', 'code' => 'QA'],
            ['name' => 'Romanya', 'code' => 'RO'],
            ['name' => 'Rusya', 'code' => 'RU'],
            ['name' => 'Ruanda', 'code' => 'RW'],
            ['name' => 'Saint Kitts ve Nevis', 'code' => 'KN'],
            ['name' => 'Saint Lucia', 'code' => 'LC'],
            ['name' => 'Saint Vincent ve Grenadinler', 'code' => 'VC'],
            ['name' => 'Samoa', 'code' => 'WS'],
            ['name' => 'San Marino', 'code' => 'SM'],
            ['name' => 'Sao Tome ve Principe', 'code' => 'ST'],
            ['name' => 'Suudi Arabistan', 'code' => 'SA'],
            ['name' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Sırbistan', 'code' => 'RS'],
            ['name' => 'Seyşeller', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Singapur', 'code' => 'SG'],
            ['name' => 'Slovakya', 'code' => 'SK'],
            ['name' => 'Slovenya', 'code' => 'SI'],
            ['name' => 'Solomon Adaları', 'code' => 'SB'],
            ['name' => 'Somali', 'code' => 'SO'],
            ['name' => 'Güney Afrika', 'code' => 'ZA'],
            ['name' => 'Güney Sudan', 'code' => 'SS'],
            ['name' => 'İspanya', 'code' => 'ES'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Sudan', 'code' => 'SD'],
            ['name' => 'Surinam', 'code' => 'SR'],
            ['name' => 'Svaziland', 'code' => 'SZ'],
            ['name' => 'İsveç', 'code' => 'SE'],
            ['name' => 'İsviçre', 'code' => 'CH'],
            ['name' => 'Suriye', 'code' => 'SY'],
            ['name' => 'Tayvan', 'code' => 'TW'],
            ['name' => 'Tacikistan', 'code' => 'TJ'],
            ['name' => 'Tanzanya', 'code' => 'TZ'],
            ['name' => 'Tayland', 'code' => 'TH'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Tonga', 'code' => 'TO'],
            ['name' => 'Trinidad ve Tobago', 'code' => 'TT'],
            ['name' => 'Tunus', 'code' => 'TN'],
            ['name' => 'Türkiye', 'code' => 'TR'],
            ['name' => 'Türkmenistan', 'code' => 'TM'],
            ['name' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ukrayna', 'code' => 'UA'],
            ['name' => 'Birleşik Arap Emirlikleri', 'code' => 'AE'],
            ['name' => 'Birleşik Krallık', 'code' => 'GB'],
            ['name' => 'Amerika Birleşik Devletleri', 'code' => 'US'],
            ['name' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Özbekistan', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'code' => 'VU'],
            ['name' => 'Vatikan', 'code' => 'VA'],
            ['name' => 'Venezuela', 'code' => 'VE'],
            ['name' => 'Vietnam', 'code' => 'VN'],
            ['name' => 'Yemen', 'code' => 'YE'],
            ['name' => 'Zambiya', 'code' => 'ZM'],
            ['name' => 'Zimbabve', 'code' => 'ZW']
        ];

        foreach ($countries as $country) {
            Country::create([
                'status' => $country['code'] === 'TR' ? Status::ACTIVE : Status::PASSIVE,
                'name' => $country['name'],
                'code' => $country['code'],
            ]);
        }
    }
}
