<?php

namespace Database\Seeders;

use Spatie\Permission\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            [
                'admin-list',
                1,
                'Listeleme'
            ],
            [
                'admin-create',
                1,
                'Ekleme'
            ],
            [
                'admin-edit',
                1,
                'Güncelleme'
            ],
            [
                'admin-delete',
                1,
                'Silme'
            ],
            [
                'role-list',
                2,
                'Listeleme'
            ],
            [
                'role-create',
                2,
                'Ekleme'
            ],
            [
                'role-edit',
                2,
                'Güncelleme'
            ],
            [
                'role-delete',
                2,
                'Silme'
            ],
            [
                'permission-list',
                3,
                'Listeleme'
            ],
            [
                'permission-create',
                3,
                'Ekleme'
            ],
            [
                'permission-edit',
                3,
                'Güncelleme'
            ],
            [
                'permission-delete',
                3,
                'Silme'
            ],
            [
                'permissiongroup-list',
                4,
                'Listeleme'
            ],
            [
                'permissiongroup-create',
                4,
                'Ekleme'
            ],
            [
                'permissiongroup-edit',
                4,
                'Güncelleme'
            ],
            [
                'permissiongroup-delete',
                4,
                'Silme'
            ],
            [
                'user-list',
                5,
                'Listeleme'
            ],
            [
                'user-create',
                5,
                'Ekleme'
            ],
            [
                'user-edit',
                5,
                'Güncelleme'
            ],
            [
                'user-delete',
                5,
                'Silme'
            ],
            [
                'setting-list',
                6,
                'Listeleme'
            ],
            [
                'setting-create',
                6,
                'Ekleme'
            ],
            [
                'setting-edit',
                6,
                'Güncelleme'
            ],
            [
                'setting-delete',
                6,
                'Silme'
            ]
         ];

         foreach ($permissions as $permission) {
            Permission::create(['name' => $permission[0], 'group_id' => $permission[1], 'text' => $permission[2]]);
         }
    }
}
