<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\Status;
use App\Models\City;
use App\Models\Country;
use App\Models\District;
use Illuminate\Database\Seeder;

class TurkiyeLocationsSeeder extends Seeder
{
    /**
     * @var array<string, string>
     */
    private const CITIES = [
        '1' => 'Adana',
        '2' => 'Adıyaman',
        '3' => 'Afyonkarahisar',
        '4' => 'Ağrı',
        '5' => 'Amasya',
        '6' => 'Ankara',
        '7' => 'Antalya',
        '8' => 'Artvin',
        '9' => 'Aydın',
        '10' => 'Balıkesir',
        '11' => 'Bilecik',
        '12' => 'Bingöl',
        '13' => 'Bitlis',
        '14' => 'Bolu',
        '15' => 'Burdur',
        '16' => 'Bursa',
        '17' => 'Çanakkale',
        '18' => 'Çankırı',
        '19' => 'Çorum',
        '20' => 'Denizli',
        '21' => 'Diyarbakır',
        '22' => 'Edirne',
        '23' => 'Elazığ',
        '24' => 'Erzincan',
        '25' => 'Erzurum',
        '26' => 'Eskişehir',
        '27' => 'Gaziantep',
        '28' => 'Giresun',
        '29' => 'Gümüşhane',
        '30' => 'Hakkari',
        '31' => 'Hatay',
        '32' => 'Isparta',
        '33' => 'Mersin',
        '34' => 'İstanbul',
        '35' => 'İzmir',
        '36' => 'Kars',
        '37' => 'Kastamonu',
        '38' => 'Kayseri',
        '39' => 'Kırklareli',
        '40' => 'Kırşehir',
        '41' => 'Kocaeli',
        '42' => 'Konya',
        '43' => 'Kütahya',
        '44' => 'Malatya',
        '45' => 'Manisa',
        '46' => 'Kahramanmaraş',
        '47' => 'Mardin',
        '48' => 'Muğla',
        '49' => 'Muş',
        '50' => 'Nevşehir',
        '51' => 'Niğde',
        '52' => 'Ordu',
        '53' => 'Rize',
        '54' => 'Sakarya',
        '55' => 'Samsun',
        '56' => 'Siirt',
        '57' => 'Sinop',
        '58' => 'Sivas',
        '59' => 'Tekirdağ',
        '60' => 'Tokat',
        '61' => 'Trabzon',
        '62' => 'Tunceli',
        '63' => 'Şanlıurfa',
        '64' => 'Uşak',
        '65' => 'Van',
        '66' => 'Yozgat',
        '67' => 'Zonguldak',
        '68' => 'Aksaray',
        '69' => 'Bayburt',
        '70' => 'Karaman',
        '71' => 'Kırıkkale',
        '72' => 'Batman',
        '73' => 'Şırnak',
        '74' => 'Bartın',
        '75' => 'Ardahan',
        '76' => 'Iğdır',
        '77' => 'Yalova',
        '78' => 'Karabük',
        '79' => 'Kilis',
        '80' => 'Osmaniye',
        '81' => 'Düzce',
    ];

    /**
     * @var array<string, list<string>>
     */
    private const DISTRICTS = [
        '1' => [
            'Seyhan',
            'Ceyhan',
            'Feke',
            'Karaisalı',
            'Karataş',
            'Kozan',
            'Pozantı',
            'Saimbeyli',
            'Tufanbeyli',
            'Yumurtalık',
            'Yüreğir',
            'Aladağ',
            'İmamoğlu',
            'Sarıçam',
            'Çukurova',
        ],
        '2' => [
            'Merkez',
            'Besni',
            'Çelikhan',
            'Gerger',
            'Gölbaşı',
            'Kahta',
            'Samsat',
            'Sincik',
            'Tut',
        ],
        '3' => [
            'Merkez',
            'Bolvadin',
            'Çay',
            'Dazkırı',
            'Dinar',
            'Emirdağ',
            'İhsaniye',
            'Sandıklı',
            'Sinanpaşa',
            'Sultandağı',
            'Şuhut',
            'Başmakçı',
            'Bayat',
            'İscehisar',
            'Çobanlar',
            'Evciler',
            'Hocalar',
            'Kızılören',
        ],
        '4' => [
            'Merkez',
            'Diyadin',
            'Doğubayazıt',
            'Eleşkirt',
            'Hamur',
            'Patnos',
            'Taşlıçay',
            'Tutak',
        ],
        '5' => [
            'Merkez',
            'Göynücek',
            'Gümüşhacıköy',
            'Merzifon',
            'Suluova',
            'Taşova',
            'Hamamözü',
        ],
        '6' => [
            'Altındağ',
            'Ayaş',
            'Bala',
            'Beypazarı',
            'Çamlıdere',
            'Çankaya',
            'Çubuk',
            'Elmadağ',
            'Güdül',
            'Haymana',
            'Kalecik',
            'Kızılcahamam',
            'Nallıhan',
            'Polatlı',
            'Şereflikoçhisar',
            'Yenimahalle',
            'Gölbaşı',
            'Keçiören',
            'Mamak',
            'Sincan',
            'Kahramankazan',
            'Akyurt',
            'Etimesgut',
            'Evren',
            'Pursaklar',
        ],
        '7' => [
            'Akseki',
            'Alanya',
            'Elmalı',
            'Finike',
            'Gazipaşa',
            'Gündoğmuş',
            'Kaş',
            'Korkuteli',
            'Kumluca',
            'Manavgat',
            'Serik',
            'Demre',
            'İbradı',
            'Kemer',
            'Aksu',
            'Döşemealtı',
            'Kepez',
            'Konyaaltı',
            'Muratpaşa',
        ],
        '8' => [
            'Ardanuç',
            'Arhavi',
            'Merkez',
            'Borçka',
            'Hopa',
            'Şavşat',
            'Yusufeli',
            'Murgul',
            'Kemalpaşa',
        ],
        '9' => [
            'Bozdoğan',
            'Çine',
            'Germencik',
            'Karacasu',
            'Koçarlı',
            'Kuşadası',
            'Kuyucak',
            'Nazilli',
            'Söke',
            'Sultanhisar',
            'Yenipazar',
            'Buharkent',
            'İncirliova',
            'Karpuzlu',
            'Köşk',
            'Didim',
            'Efeler',
        ],
        '10' => [
            'Ayvalık',
            'Balya',
            'Bandırma',
            'Bigadiç',
            'Burhaniye',
            'Dursunbey',
            'Edremit',
            'Erdek',
            'Gönen',
            'Havran',
            'İvrindi',
            'Kepsut',
            'Manyas',
            'Savaştepe',
            'Sındırgı',
            'Susurluk',
            'Marmara',
            'Gömeç',
            'Altıeylül',
            'Karesi',
        ],
        '11' => [
            'Merkez',
            'Bozüyük',
            'Gölpazarı',
            'Osmaneli',
            'Pazaryeri',
            'Söğüt',
            'Yenipazar',
            'İnhisar',
        ],
        '12' => [
            'Merkez',
            'Genç',
            'Karlıova',
            'Kiğı',
            'Solhan',
            'Adaklı',
            'Yayladere',
            'Yedisu',
        ],
        '13' => [
            'Adilcevaz',
            'Ahlat',
            'Merkez',
            'Hizan',
            'Mutki',
            'Tatvan',
            'Güroymak',
        ],
        '14' => [
            'Merkez',
            'Gerede',
            'Göynük',
            'Kıbrıscık',
            'Mengen',
            'Mudurnu',
            'Seben',
            'Dörtdivan',
            'Yeniçağa',
        ],
        '15' => [
            'Ağlasun',
            'Bucak',
            'Merkez',
            'Gölhisar',
            'Tefenni',
            'Yeşilova',
            'Karamanlı',
            'Kemer',
            'Altınyayla',
            'Çavdır',
            'Çeltikçi',
        ],
        '16' => [
            'Gemlik',
            'İnegöl',
            'İznik',
            'Karacabey',
            'Keles',
            'Mudanya',
            'Mustafakemalpaşa',
            'Orhaneli',
            'Orhangazi',
            'Yenişehir',
            'Büyükorhan',
            'Harmancık',
            'Nilüfer',
            'Osmangazi',
            'Yıldırım',
            'Gürsu',
            'Kestel',
        ],
        '17' => [
            'Ayvacık',
            'Bayramiç',
            'Biga',
            'Bozcaada',
            'Çan',
            'Merkez',
            'Eceabat',
            'Ezine',
            'Gelibolu',
            'Gökçeada',
            'Lapseki',
            'Yenice',
        ],
        '18' => [
            'Merkez',
            'Çerkeş',
            'Eldivan',
            'Ilgaz',
            'Kurşunlu',
            'Orta',
            'Şabanözü',
            'Yapraklı',
            'Atkaracalar',
            'Kızılırmak',
            'Bayramören',
            'Korgun',
        ],
        '19' => [
            'Alaca',
            'Bayat',
            'Merkez',
            'İskilip',
            'Kargı',
            'Mecitözü',
            'Ortaköy',
            'Osmancık',
            'Sungurlu',
            'Boğazkale',
            'Uğurludağ',
            'Dodurga',
            'Laçin',
            'Oğuzlar',
        ],
        '20' => [
            'Acıpayam',
            'Buldan',
            'Çal',
            'Çameli',
            'Çardak',
            'Çivril',
            'Güney',
            'Kale',
            'Sarayköy',
            'Tavas',
            'Babadağ',
            'Bekilli',
            'Honaz',
            'Serinhisar',
            'Pamukkale',
            'Baklan',
            'Beyağaç',
            'Bozkurt',
            'Merkezefendi',
        ],
        '21' => [
            'Bismil',
            'Çermik',
            'Çınar',
            'Çüngüş',
            'Dicle',
            'Ergani',
            'Hani',
            'Hazro',
            'Kulp',
            'Lice',
            'Silvan',
            'Eğil',
            'Kocaköy',
            'Bağlar',
            'Kayapınar',
            'Sur',
            'Yenişehir',
        ],
        '22' => [
            'Merkez',
            'Enez',
            'Havsa',
            'İpsala',
            'Keşan',
            'Lalapaşa',
            'Meriç',
            'Uzunköprü',
            'Süloğlu',
        ],
        '23' => [
            'Ağın',
            'Baskil',
            'Merkez',
            'Karakoçan',
            'Keban',
            'Maden',
            'Palu',
            'Sivrice',
            'Arıcak',
            'Kovancılar',
            'Alacakaya',
        ],
        '24' => [
            'Çayırlı',
            'Merkez',
            'İliç',
            'Kemah',
            'Kemaliye',
            'Refahiye',
            'Tercan',
            'Üzümlü',
            'Otlukbeli',
        ],
        '25' => [
            'Aşkale',
            'Çat',
            'Hınıs',
            'Horasan',
            'İspir',
            'Karayazı',
            'Narman',
            'Oltu',
            'Olur',
            'Pasinler',
            'Şenkaya',
            'Tekman',
            'Tortum',
            'Karaçoban',
            'Uzundere',
            'Pazaryolu',
            'Aziziye',
            'Köprüköy',
            'Palandöken',
            'Yakutiye',
        ],
        '26' => [
            'Çifteler',
            'Mahmudiye',
            'Mihalıççık',
            'Sarıcakaya',
            'Seyitgazi',
            'Sivrihisar',
            'Alpu',
            'Beylikova',
            'İnönü',
            'Günyüzü',
            'Han',
            'Mihalgazi',
            'Odunpazarı',
            'Tepebaşı',
        ],
        '27' => [
            'Araban',
            'İslahiye',
            'Nizip',
            'Oğuzeli',
            'Yavuzeli',
            'Şahinbey',
            'Şehitkamil',
            'Karkamış',
            'Nurdağı',
        ],
        '28' => [
            'Alucra',
            'Bulancak',
            'Dereli',
            'Espiye',
            'Eynesil',
            'Merkez',
            'Görele',
            'Keşap',
            'Şebinkarahisar',
            'Tirebolu',
            'Piraziz',
            'Yağlıdere',
            'Çamoluk',
            'Çanakçı',
            'Doğankent',
            'Güce',
        ],
        '29' => [
            'Merkez',
            'Kelkit',
            'Şiran',
            'Torul',
            'Köse',
            'Kürtün',
        ],
        '30' => [
            'Çukurca',
            'Merkez',
            'Şemdinli',
            'Yüksekova',
            'Derecik',
        ],
        '31' => [
            'Altınözü',
            'Dörtyol',
            'Hassa',
            'İskenderun',
            'Kırıkhan',
            'Reyhanlı',
            'Samandağ',
            'Yayladağı',
            'Erzin',
            'Belen',
            'Kumlu',
            'Antakya',
            'Arsuz',
            'Defne',
            'Payas',
        ],
        '32' => [
            'Atabey',
            'Eğirdir',
            'Gelendost',
            'Merkez',
            'Keçiborlu',
            'Senirkent',
            'Sütçüler',
            'Şarkikaraağaç',
            'Uluborlu',
            'Yalvaç',
            'Aksu',
            'Gönen',
            'Yenişarbademli',
        ],
        '33' => [
            'Anamur',
            'Erdemli',
            'Gülnar',
            'Mut',
            'Silifke',
            'Tarsus',
            'Aydıncık',
            'Bozyazı',
            'Çamlıyayla',
            'Akdeniz',
            'Mezitli',
            'Toroslar',
            'Yenişehir',
        ],
        '34' => [
            'Adalar',
            'Bakırköy',
            'Beşiktaş',
            'Beykoz',
            'Beyoğlu',
            'Çatalca',
            'Eyüpsultan',
            'Fatih',
            'Gaziosmanpaşa',
            'Kadıköy',
            'Kartal',
            'Sarıyer',
            'Silivri',
            'Şile',
            'Şişli',
            'Üsküdar',
            'Zeytinburnu',
            'Büyükçekmece',
            'Kağıthane',
            'Küçükçekmece',
            'Pendik',
            'Ümraniye',
            'Bayrampaşa',
            'Avcılar',
            'Bağcılar',
            'Bahçelievler',
            'Güngören',
            'Maltepe',
            'Sultanbeyli',
            'Tuzla',
            'Esenler',
            'Arnavutköy',
            'Ataşehir',
            'Başakşehir',
            'Beylikdüzü',
            'Çekmeköy',
            'Esenyurt',
            'Sancaktepe',
            'Sultangazi',
        ],
        '35' => [
            'Aliağa',
            'Bayındır',
            'Bergama',
            'Bornova',
            'Çeşme',
            'Dikili',
            'Foça',
            'Karaburun',
            'Karşıyaka',
            'Kemalpaşa',
            'Kınık',
            'Kiraz',
            'Menemen',
            'Ödemiş',
            'Seferihisar',
            'Selçuk',
            'Tire',
            'Torbalı',
            'Urla',
            'Beydağ',
            'Buca',
            'Konak',
            'Menderes',
            'Balçova',
            'Çiğli',
            'Gaziemir',
            'Narlıdere',
            'Güzelbahçe',
            'Bayraklı',
            'Karabağlar',
        ],
        '36' => [
            'Arpaçay',
            'Digor',
            'Kağızman',
            'Merkez',
            'Sarıkamış',
            'Selim',
            'Susuz',
            'Akyaka',
        ],
        '37' => [
            'Abana',
            'Araç',
            'Azdavay',
            'Bozkurt',
            'Cide',
            'Çatalzeytin',
            'Daday',
            'Devrekani',
            'İnebolu',
            'Merkez',
            'Küre',
            'Taşköprü',
            'Tosya',
            'İhsangazi',
            'Pınarbaşı',
            'Şenpazar',
            'Ağlı',
            'Doğanyurt',
            'Hanönü',
            'Seydiler',
        ],
        '38' => [
            'Bünyan',
            'Develi',
            'Felahiye',
            'İncesu',
            'Pınarbaşı',
            'Sarıoğlan',
            'Sarız',
            'Tomarza',
            'Yahyalı',
            'Yeşilhisar',
            'Akkışla',
            'Talas',
            'Kocasinan',
            'Melikgazi',
            'Hacılar',
            'Özvatan',
        ],
        '39' => [
            'Babaeski',
            'Demirköy',
            'Merkez',
            'Kofçaz',
            'Lüleburgaz',
            'Pehlivanköy',
            'Pınarhisar',
            'Vize',
        ],
        '40' => [
            'Çiçekdağı',
            'Kaman',
            'Merkez',
            'Mucur',
            'Akpınar',
            'Akçakent',
            'Boztepe',
        ],
        '41' => [
            'Gebze',
            'Gölcük',
            'Kandıra',
            'Karamürsel',
            'Körfez',
            'Derince',
            'Başiskele',
            'Çayırova',
            'Darıca',
            'Dilovası',
            'İzmit',
            'Kartepe',
        ],
        '42' => [
            'Akşehir',
            'Beyşehir',
            'Bozkır',
            'Cihanbeyli',
            'Çumra',
            'Doğanhisar',
            'Ereğli',
            'Hadim',
            'Ilgın',
            'Kadınhanı',
            'Karapınar',
            'Kulu',
            'Sarayönü',
            'Seydişehir',
            'Yunak',
            'Akören',
            'Altınekin',
            'Derebucak',
            'Hüyük',
            'Karatay',
            'Meram',
            'Selçuklu',
            'Taşkent',
            'Ahırlı',
            'Çeltik',
            'Derbent',
            'Emirgazi',
            'Güneysınır',
            'Halkapınar',
            'Tuzlukçu',
            'Yalıhüyük',
        ],
        '43' => [
            'Altıntaş',
            'Domaniç',
            'Emet',
            'Gediz',
            'Merkez',
            'Simav',
            'Tavşanlı',
            'Aslanapa',
            'Dumlupınar',
            'Hisarcık',
            'Şaphane',
            'Çavdarhisar',
            'Pazarlar',
        ],
        '44' => [
            'Akçadağ',
            'Arapgir',
            'Arguvan',
            'Darende',
            'Doğanşehir',
            'Hekimhan',
            'Pütürge',
            'Yeşilyurt',
            'Battalgazi',
            'Doğanyol',
            'Kale',
            'Kuluncak',
            'Yazıhan',
        ],
        '45' => [
            'Akhisar',
            'Alaşehir',
            'Demirci',
            'Gördes',
            'Kırkağaç',
            'Kula',
            'Salihli',
            'Sarıgöl',
            'Saruhanlı',
            'Selendi',
            'Soma',
            'Turgutlu',
            'Ahmetli',
            'Gölmarmara',
            'Köprübaşı',
            'Şehzadeler',
            'Yunusemre',
        ],
        '46' => [
            'Afşin',
            'Andırın',
            'Elbistan',
            'Göksun',
            'Pazarcık',
            'Türkoğlu',
            'Çağlayancerit',
            'Ekinözü',
            'Nurhak',
            'Dulkadiroğlu',
            'Onikişubat',
        ],
        '47' => [
            'Derik',
            'Kızıltepe',
            'Mazıdağı',
            'Midyat',
            'Nusaybin',
            'Ömerli',
            'Savur',
            'Dargeçit',
            'Yeşilli',
            'Artuklu',
        ],
        '48' => [
            'Bodrum',
            'Datça',
            'Fethiye',
            'Köyceğiz',
            'Marmaris',
            'Milas',
            'Ula',
            'Yatağan',
            'Dalaman',
            'Ortaca',
            'Kavaklıdere',
            'Menteşe',
            'Seydikemer',
        ],
        '49' => [
            'Bulanık',
            'Malazgirt',
            'Merkez',
            'Varto',
            'Hasköy',
            'Korkut',
        ],
        '50' => [
            'Avanos',
            'Derinkuyu',
            'Gülşehir',
            'Hacıbektaş',
            'Kozaklı',
            'Merkez',
            'Ürgüp',
            'Acıgöl',
        ],
        '51' => [
            'Bor',
            'Çamardı',
            'Merkez',
            'Ulukışla',
            'Altunhisar',
            'Çiftlik',
        ],
        '52' => [
            'Akkuş',
            'Aybastı',
            'Fatsa',
            'Gölköy',
            'Korgan',
            'Kumru',
            'Mesudiye',
            'Perşembe',
            'Ulubey',
            'Ünye',
            'Gülyalı',
            'Gürgentepe',
            'Çamaş',
            'Çatalpınar',
            'Çaybaşı',
            'İkizce',
            'Kabadüz',
            'Kabataş',
            'Altınordu',
        ],
        '53' => [
            'Ardeşen',
            'Çamlıhemşin',
            'Çayeli',
            'Fındıklı',
            'İkizdere',
            'Kalkandere',
            'Pazar',
            'Merkez',
            'Güneysu',
            'Derepazarı',
            'Hemşin',
            'İyidere',
        ],
        '54' => [
            'Akyazı',
            'Geyve',
            'Hendek',
            'Karasu',
            'Kaynarca',
            'Sapanca',
            'Kocaali',
            'Pamukova',
            'Taraklı',
            'Ferizli',
            'Karapürçek',
            'Söğütlü',
            'Adapazarı',
            'Arifiye',
            'Erenler',
            'Serdivan',
        ],
        '55' => [
            'Alaçam',
            'Bafra',
            'Çarşamba',
            'Havza',
            'Kavak',
            'Ladik',
            'Terme',
            'Vezirköprü',
            'Asarcık',
            '19 Mayıs',
            'Salıpazarı',
            'Tekkeköy',
            'Ayvacık',
            'Yakakent',
            'Atakum',
            'Canik',
            'İlkadım',
        ],
        '56' => [
            'Baykan',
            'Eruh',
            'Kurtalan',
            'Pervari',
            'Merkez',
            'Şirvan',
            'Tillo',
        ],
        '57' => [
            'Ayancık',
            'Boyabat',
            'Durağan',
            'Erfelek',
            'Gerze',
            'Merkez',
            'Türkeli',
            'Dikmen',
            'Saraydüzü',
        ],
        '58' => [
            'Divriği',
            'Gemerek',
            'Gürün',
            'Hafik',
            'İmranlı',
            'Kangal',
            'Koyulhisar',
            'Merkez',
            'Suşehri',
            'Şarkışla',
            'Yıldızeli',
            'Zara',
            'Akıncılar',
            'Altınyayla',
            'Doğanşar',
            'Gölova',
            'Ulaş',
        ],
        '59' => [
            'Çerkezköy',
            'Çorlu',
            'Hayrabolu',
            'Malkara',
            'Muratlı',
            'Saray',
            'Şarköy',
            'Marmaraereğlisi',
            'Ergene',
            'Kapaklı',
            'Süleymanpaşa',
        ],
        '60' => [
            'Almus',
            'Artova',
            'Erbaa',
            'Niksar',
            'Reşadiye',
            'Merkez',
            'Turhal',
            'Zile',
            'Pazar',
            'Yeşilyurt',
            'Başçiftlik',
            'Sulusaray',
        ],
        '61' => [
            'Akçaabat',
            'Araklı',
            'Arsin',
            'Çaykara',
            'Maçka',
            'Of',
            'Sürmene',
            'Tonya',
            'Vakfıkebir',
            'Yomra',
            'Beşikdüzü',
            'Şalpazarı',
            'Çarşıbaşı',
            'Dernekpazarı',
            'Düzköy',
            'Hayrat',
            'Köprübaşı',
            'Ortahisar',
        ],
        '62' => [
            'Çemişgezek',
            'Hozat',
            'Mazgirt',
            'Nazımiye',
            'Ovacık',
            'Pertek',
            'Pülümür',
            'Merkez',
        ],
        '63' => [
            'Akçakale',
            'Birecik',
            'Bozova',
            'Ceylanpınar',
            'Halfeti',
            'Hilvan',
            'Siverek',
            'Suruç',
            'Viranşehir',
            'Harran',
            'Eyyübiye',
            'Haliliye',
            'Karaköprü',
        ],
        '64' => [
            'Banaz',
            'Eşme',
            'Karahallı',
            'Sivaslı',
            'Ulubey',
            'Merkez',
        ],
        '65' => [
            'Başkale',
            'Çatak',
            'Erciş',
            'Gevaş',
            'Gürpınar',
            'Muradiye',
            'Özalp',
            'Bahçesaray',
            'Çaldıran',
            'Edremit',
            'Saray',
            'İpekyolu',
            'Tuşba',
        ],
        '66' => [
            'Akdağmadeni',
            'Boğazlıyan',
            'Çayıralan',
            'Çekerek',
            'Sarıkaya',
            'Sorgun',
            'Şefaatli',
            'Yerköy',
            'Merkez',
            'Aydıncık',
            'Çandır',
            'Kadışehri',
            'Saraykent',
            'Yenifakılı',
        ],
        '67' => [
            'Çaycuma',
            'Devrek',
            'Ereğli',
            'Merkez',
            'Alaplı',
            'Gökçebey',
            'Kilimli',
            'Kozlu',
        ],
        '68' => [
            'Merkez',
            'Ortaköy',
            'Ağaçören',
            'Güzelyurt',
            'Sarıyahşi',
            'Eskil',
            'Gülağaç',
            'Sultanhanı',
        ],
        '69' => [
            'Merkez',
            'Aydıntepe',
            'Demirözü',
        ],
        '70' => [
            'Ermenek',
            'Merkez',
            'Ayrancı',
            'Kazımkarabekir',
            'Başyayla',
            'Sarıveliler',
        ],
        '71' => [
            'Delice',
            'Keskin',
            'Merkez',
            'Sulakyurt',
            'Bahşılı',
            'Balışeyh',
            'Çelebi',
            'Karakeçili',
            'Yahşihan',
        ],
        '72' => [
            'Merkez',
            'Beşiri',
            'Gercüş',
            'Kozluk',
            'Sason',
            'Hasankeyf',
        ],
        '73' => [
            'Beytüşşebap',
            'Cizre',
            'İdil',
            'Silopi',
            'Merkez',
            'Uludere',
            'Güçlükonak',
        ],
        '74' => [
            'Merkez',
            'Kurucaşile',
            'Ulus',
            'Amasra',
        ],
        '75' => [
            'Merkez',
            'Çıldır',
            'Göle',
            'Hanak',
            'Posof',
            'Damal',
        ],
        '76' => [
            'Aralık',
            'Merkez',
            'Tuzluca',
            'Karakoyunlu',
        ],
        '77' => [
            'Merkez',
            'Altınova',
            'Armutlu',
            'Çınarcık',
            'Çiftlikköy',
            'Termal',
        ],
        '78' => [
            'Eflani',
            'Eskipazar',
            'Merkez',
            'Ovacık',
            'Safranbolu',
            'Yenice',
        ],
        '79' => [
            'Merkez',
            'Elbeyli',
            'Musabeyli',
            'Polateli',
        ],
        '80' => [
            'Bahçe',
            'Kadirli',
            'Merkez',
            'Düziçi',
            'Hasanbeyli',
            'Sumbas',
            'Toprakkale',
        ],
        '81' => [
            'Akçakoca',
            'Merkez',
            'Yığılca',
            'Cumayeri',
            'Gölyaka',
            'Çilimli',
            'Gümüşova',
            'Kaynaşlı',
        ],
    ];

    public function run(): void
    {
        $country = Country::query()->updateOrCreate(
            ['code' => 'TR'],
            [
                'name' => 'Türkiye',
                'status' => Status::Active,
                'sort_order' => 1,
            ],
        );

        $cityMap = $this->seedCities($country);

        $this->seedDistricts($cityMap);
    }

    /**
     * @return array<string, City>
     */
    private function seedCities(Country $country): array
    {
        $cityMap = [];

        foreach (self::CITIES as $cityCode => $cityName) {
            $city = City::withTrashed()->updateOrCreate(
                [
                    'country_id' => $country->id,
                    'code' => $cityCode,
                ],
                [
                    'name' => $cityName,
                    'status' => Status::Active,
                    'sort_order' => (int) $cityCode,
                ],
            );

            if ($city->trashed()) {
                $city->restore();
            }

            $cityMap[$cityCode] = $city;
        }

        return $cityMap;
    }

    /**
     * @param  array<string, City>  $cityMap
     */
    private function seedDistricts(array $cityMap): void
    {
        foreach (self::DISTRICTS as $cityCode => $districtNames) {
            $city = $cityMap[$cityCode] ?? null;

            if (! $city instanceof City) {
                continue;
            }

            foreach ($districtNames as $index => $districtName) {
                $district = District::withTrashed()->updateOrCreate(
                    [
                        'city_id' => $city->id,
                        'name' => $districtName,
                    ],
                    [
                        'status' => Status::Active,
                        'sort_order' => $index + 1,
                    ],
                );

                if ($district->trashed()) {
                    $district->restore();
                }
            }
        }
    }
}
