<?php

namespace App\Support;

class Helper
{

    /**
     * Renk kodunun koyuluğuna göre font kodunu ayarlama
     * https://stackoverflow.com/questions/12228644/how-to-detect-light-colors-with-php
     */
    public static function isDark($hex)
    {
        $average = 381; // range 1 - 765
        if (strlen(trim($hex)) == 4) {
            $hex = "#" . substr($hex, 1, 1) . substr($hex, 1, 1) . substr($hex, 2, 1) . substr($hex, 2, 1) . substr($hex, 3, 1) . substr($hex, 3, 1);
        }
        return ((hexdec(substr($hex, 1, 2)) + hexdec(substr($hex, 3, 2)) + hexdec(substr($hex, 5, 2)) < $average) ? true : false);
    }

    /**
     * Get part of string.
     * @param string $string
     * @param int $start
     * @param int $end
     * @return string
     * Örnek Kullanım: Helper::shortString($post->body,0,40)
     * Girilen içeriğin başlangıçtan kırkıncı karaktere kadar olan bölümünü alır
     * Kaynak: https://blog.corelux.com.tr/laravelde-kendi-helper-sinifimizi-olusturmak
     */
    public static function shortString(string $string, int $start = 0, int $end = 35): string
    {
        return mb_substr($string, $start, $end, 'UTF-8') . '...';
    }

    /**
     * Timezones
     *
     * List of timezones
     */
    public static function timezones()
    {
        return $timezones = [
            'Afrika' => [
                'Africa/Abidjan' => 'Abidjan',
                'Africa/Accra' => 'Accra',
                'Africa/Addis_Ababa' => 'Addis Ababa',
                'Africa/Algiers' => 'Algiers',
                'Africa/Asmara' => 'Asmara',
                'Africa/Bamako' => 'Bamako',
                'Africa/Bangui' => 'Bangui',
                'Africa/Banjul' => 'Banjul',
                'Africa/Bissau' => 'Bissau',
                'Africa/Blantyre' => 'Blantyre',
                'Africa/Brazzaville' => 'Brazzaville',
                'Africa/Bujumbura' => 'Bujumbura',
                'Africa/Cairo' => 'Cairo',
                'Africa/Casablanca' => 'Casablanca',
                'Africa/Ceuta' => 'Ceuta',
                'Africa/Conakry' => 'Conakry',
                'Africa/Dakar' => 'Dakar',
                'Africa/Dar_es_Salaam' => 'Dar es Salaam',
                'Africa/Djibouti' => 'Djibouti',
                'Africa/Douala' => 'Douala',
                'Africa/El_Aaiun' => 'El Aaiun',
                'Africa/Freetown' => 'Freetown',
                'Africa/Gaborone' => 'Gaborone',
                'Africa/Harare' => 'Harare',
                'Africa/Johannesburg' => 'Johannesburg',
                'Africa/Juba' => 'Juba',
                'Africa/Kampala' => 'Kampala',
                'Africa/Khartoum' => 'Khartoum',
                'Africa/Kigali' => 'Kigali',
                'Africa/Kinshasa' => 'Kinshasa',
                'Africa/Lagos' => 'Lagos',
                'Africa/Libreville' => 'Libreville',
                'Africa/Lome' => 'Lome',
                'Africa/Luanda' => 'Luanda',
                'Africa/Lubumbashi' => 'Lubumbashi',
                'Africa/Lusaka' => 'Lusaka',
                'Africa/Malabo' => 'Malabo',
                'Africa/Maputo' => 'Maputo',
                'Africa/Maseru' => 'Maseru',
                'Africa/Mbabane' => 'Mbabane',
                'Africa/Mogadishu' => 'Mogadishu',
                'Africa/Monrovia' => 'Monrovia',
                'Africa/Nairobi' => 'Nairobi',
                'Africa/Ndjamena' => 'Ndjamena',
                'Africa/Niamey' => 'Niamey',
                'Africa/Nouakchott' => 'Nouakchott',
                'Africa/Ouagadougou' => 'Ouagadougou',
                'Africa/Porto-Novo' => 'Porto-Novo',
                'Africa/Sao_Tome' => 'Sao Tome',
                'Africa/Tripoli' => 'Tripoli',
                'Africa/Tunis' => 'Tunis',
                'Africa/Windhoek' => 'Windhoek'
            ],
            'America' => [
                'America/Adak' => 'Adak',
                'America/Anchorage' => 'Anchorage',
                'America/Anguilla' => 'Anguilla',
                'America/Antigua' => 'Antigua',
                'America/Araguaina' => 'Araguaina',
                'America/Argentina/Buenos_Aires' => 'Arjantin - Buenos Aires',
                'America/Argentina/Catamarca' => 'Arjantin - Catamarca',
                'America/Argentina/Jujuy' => 'Arjantin - Jujuy',
                'America/Argentina/Cordoba' => 'Arjantin - Kurtuba',
                'America/Argentina/La_Rioja' => 'Arjantin - La Rioja',
                'America/Argentina/Mendoza' => 'Arjantin - Mendoza',
                'America/Argentina/Rio_Gallegos' => 'Arjantin - Rio Gallegos',
                'America/Argentina/Salta' => 'Arjantin - Salta',
                'America/Argentina/San_Juan' => 'Arjantin - San Juan',
                'America/Argentina/San_Luis' => 'Arjantin - San Luis',
                'America/Argentina/Tucuman' => 'Arjantin - Tucuman',
                'America/Argentina/Ushuaia' => 'Arjantin - Ushuaia',
                'America/Aruba' => 'Aruba',
                'America/Asuncion' => 'Asuncion',
                'America/Atikokan' => 'Atikokan',
                'America/Bahia' => 'Bahia',
                'America/Bahia_Banderas' => 'Bahia Banderas',
                'America/Barbados' => 'Barbados',
                'America/Belem' => 'Belem',
                'America/Belize' => 'Belize',
                'America/Blanc-Sablon' => 'Blanc-Sablon',
                'America/Boa_Vista' => 'Boa Vista',
                'America/Bogota' => 'Bogota',
                'America/Boise' => 'Boise',
                'America/Cambridge_Bay' => 'Cambridge Bay',
                'America/Campo_Grande' => 'Campo Grande',
                'America/Cancun' => 'Cancun',
                'America/Caracas' => 'Caracas',
                'America/Cayenne' => 'Cayenne',
                'America/Cayman' => 'Cayman',
                'America/Chihuahua' => 'Chihuahua',
                'America/Creston' => 'Creston',
                'America/Cuiaba' => 'Cuiaba',
                'America/Curacao' => 'Curacao',
                'America/Danmarkshavn' => 'Danmarkshavn',
                'America/Dawson' => 'Dawson',
                'America/Dawson_Creek' => 'Dawson Creek',
                'America/Denver' => 'Denver',
                'America/Detroit' => 'Detroit',
                'America/Dominica' => 'Dominica',
                'America/Edmonton' => 'Edmonton',
                'America/Eirunepe' => 'Eirunepe',
                'America/El_Salvador' => 'El Salvador',
                'America/Fortaleza' => 'Fortaleza',
                'America/Fort_Nelson' => 'Fort Nelson',
                'America/Glace_Bay' => 'Glace Bay',
                'America/Goose_Bay' => 'Goose Bay',
                'America/Grand_Turk' => 'Grand Turk',
                'America/Grenada' => 'Grenada',
                'America/Guadeloupe' => 'Guadeloupe',
                'America/Guatemala' => 'Guatemala',
                'America/Guayaquil' => 'Guayaquil',
                'America/Guyana' => 'Guyana',
                'America/Halifax' => 'Halifax',
                'America/Havana' => 'Havana',
                'America/Hermosillo' => 'Hermosillo',
                'America/Indiana/Indianapolis' => 'Indiana - Indianapolis',
                'America/Indiana/Knox' => 'Indiana - Knox',
                'America/Indiana/Marengo' => 'Indiana - Marengo',
                'America/Indiana/Petersburg' => 'Indiana - Petersburg',
                'America/Indiana/Tell_City' => 'Indiana - Tell City',
                'America/Indiana/Vevay' => 'Indiana - Vevay',
                'America/Indiana/Vincennes' => 'Indiana - Vincennes',
                'America/Indiana/Winamac' => 'Indiana - Winamac',
                'America/Inuvik' => 'Inuvik',
                'America/Iqaluit' => 'Iqaluit',
                'America/Jamaica' => 'Jamaika',
                'America/Juneau' => 'Juneau',
                'America/Kentucky/Louisville' => 'Kentucky - Louisville',
                'America/Kentucky/Monticello' => 'Kentucky - Monticello',
                'America/Costa_Rica' => 'Kosta Rika',
                'America/Kralendijk' => 'Kralendijk',
                'America/North_Dakota/Beulah' => 'Kuzey Dakota - Beulah',
                'America/North_Dakota/Center' => 'Kuzey Dakota - Merkez',
                'America/North_Dakota/New_Salem' => 'Kuzey Dakota - New Salem',
                'America/La_Paz' => 'La Paz',
                'America/Lima' => 'Lima',
                'America/Los_Angeles' => 'Los Angeles',
                'America/Lower_Princes' => 'Lower Princes',
                'America/Maceio' => 'Maceio',
                'America/Managua' => 'Managua',
                'America/Manaus' => 'Manaus',
                'America/Marigot' => 'Marigot',
                'America/Martinique' => 'Martinique',
                'America/Matamoros' => 'Matamoros',
                'America/Mazatlan' => 'Mazatlan',
                'America/Mexico_City' => 'Meksika',
                'America/Menominee' => 'Menominee',
                'America/Merida' => 'Merida',
                'America/Metlakatla' => 'Metlakatla',
                'America/Miquelon' => 'Miquelon',
                'America/Moncton' => 'Moncton',
                'America/Monterrey' => 'Monterrey',
                'America/Montevideo' => 'Montevideo',
                'America/Montserrat' => 'Montserrat',
                'America/Nassau' => 'Nassau',
                'America/New_York' => 'New York',
                'America/Nome' => 'Nome',
                'America/Noronha' => 'Noronha',
                'America/Nuuk' => 'Nuuk',
                'America/Ojinaga' => 'Ojinaga',
                'America/Panama' => 'Panama',
                'America/Pangnirtung' => 'Pangnirtung',
                'America/Paramaribo' => 'Paramaribo',
                'America/Phoenix' => 'Phoenix',
                'America/Port-au-Prince' => 'Port-au-Prince',
                'America/Port_of_Spain' => 'Port of Spain',
                'America/Puerto_Rico' => 'Porto Riko',
                'America/Porto_Velho' => 'Porto Velho',
                'America/Punta_Arenas' => 'Punta Arena',
                'America/Rankin_Inlet' => 'Rankin Inlet',
                'America/Recife' => 'Recife',
                'America/Regina' => 'Regina',
                'America/Resolute' => 'Resolute',
                'America/Rio_Branco' => 'Rio Branco',
                'America/Santarem' => 'Santarem',
                'America/Santiago' => 'Santiago',
                'America/Santo_Domingo' => 'Santo Domingo',
                'America/Sao_Paulo' => 'Sao Paulo',
                'America/Scoresbysund' => 'Scoresbysund',
                'America/Sitka' => 'Sitka',
                'America/St_Barthelemy' => 'St Barthelemy',
                'America/St_Johns' => 'St Johns',
                'America/St_Kitts' => 'St Kitts',
                'America/St_Lucia' => 'St Lucia',
                'America/St_Thomas' => 'St Thomas',
                'America/St_Vincent' => 'St Vincent',
                'America/Swift_Current' => 'Swift Current',
                'America/Tegucigalpa' => 'Tegucigalpa',
                'America/Thule' => 'Thule',
                'America/Tijuana' => 'Tijuana',
                'America/Toronto' => 'Toronto',
                'America/Tortola' => 'Tortola',
                'America/Vancouver' => 'Vancouver',
                'America/Whitehorse' => 'Whitehorse',
                'America/Winnipeg' => 'Winnipeg',
                'America/Yakutat' => 'Yakutat',
                'America/Yellowknife' => 'Yellowknife',
                'America/Chicago' => 'Chicago'
            ],
            'Antarctica' => [
                'Antarctica/Casey' => 'Casey',
                'Antarctica/Davis' => 'Davis',
                'Antarctica/DumontDUrville' => 'DumontDUrville',
                'Antarctica/Macquarie' => 'Macquarie',
                'Antarctica/Mawson' => 'Mawson',
                'Antarctica/McMurdo' => 'McMurdo',
                'Antarctica/Palmer' => 'Palmer',
                'Antarctica/Rothera' => 'Rothera',
                'Antarctica/Syowa' => 'Syowa',
                'Antarctica/Troll' => 'Troll',
                'Antarctica/Vostok' => 'Vostok'
            ],
            'Arctic' => [
                'Arctic/Longyearbyen' => 'Longyearbyen'
            ],
            'Asia' => [
                'Asia/Aden' => 'Aden',
                'Asia/Almaty' => 'Almaty',
                'Asia/Amman' => 'Amman',
                'Asia/Anadyr' => 'Anadyr',
                'Asia/Aqtau' => 'Aqtau',
                'Asia/Aqtobe' => 'Aqtobe',
                'Asia/Ashgabat' => 'Ashgabat',
                'Asia/Atyrau' => 'Atiro',
                'Asia/Bahrain' => 'Bahreyn',
                'Asia/Baku' => 'Bakü',
                'Asia/Bangkok' => 'Bangok',
                'Asia/Barnaul' => 'Barnaul',
                'Asia/Baghdad' => 'Bağdat',
                'Asia/Beirut' => 'Beyrut',
                'Asia/Bishkek' => 'Bişkek',
                'Asia/Brunei' => 'Brunei',
                'Asia/Jakarta' => 'Cakarta',
                'Asia/Chita' => 'Chita',
                'Asia/Choibalsan' => 'Choibalsan',
                'Asia/Colombo' => 'Colombo',
                'Asia/Dhaka' => 'Dhaka',
                'Asia/Dili' => 'Dili',
                'Asia/Dubai' => 'Dubai',
                'Asia/Dushanbe' => 'Dushanbe',
                'Asia/Famagusta' => 'Famagusta',
                'Asia/Gaza' => 'Gazze',
                'Asia/Hebron' => 'Hebron',
                'Asia/Ho_Chi_Minh' => 'Ho Chi Minh',
                'Asia/Hong_Kong' => 'Hong Kong',
                'Asia/Hovd' => 'Hovd',
                'Asia/Irkutsk' => 'Irkutsk',
                'Asia/Jayapura' => 'Jayapura',
                'Asia/Kamchatka' => 'Kamçatka',
                'Asia/Khandyga' => 'Kandiga',
                'Asia/Karachi' => 'Karaçi',
                'Asia/Qatar' => 'Katar',
                'Asia/Kathmandu' => 'Katmandu',
                'Asia/Kolkata' => 'Kolkata',
                'Asia/Krasnoyarsk' => 'Krasnoyarsk',
                'Asia/Kuala_Lumpur' => 'Kuala Lumpur',
                'Asia/Kuching' => 'Kuching',
                'Asia/Jerusalem' => 'Kudüs',
                'Asia/Kuwait' => 'Kuveyt',
                'Asia/Kabul' => 'Kâbil',
                'Asia/Macau' => 'Macau',
                'Asia/Magadan' => 'Magadan',
                'Asia/Makassar' => 'Makassar',
                'Asia/Manila' => 'Manila',
                'Asia/Muscat' => 'Muscat',
                'Asia/Nicosia' => 'Nicosia',
                'Asia/Novokuznetsk' => 'Novokuznetsk',
                'Asia/Novosibirsk' => 'Novosibirsk',
                'Asia/Omsk' => 'Omsk',
                'Asia/Oral' => 'Oral',
                'Asia/Phnom_Penh' => 'Phnom Penh',
                'Asia/Pontianak' => 'Pontianak',
                'Asia/Pyongyang' => 'Pyongyang',
                'Asia/Qostanay' => 'Qostanay',
                'Asia/Qyzylorda' => 'Qyzylorda',
                'Asia/Riyadh' => 'Riyadh',
                'Asia/Sakhalin' => 'Sakhalin',
                'Asia/Samarkand' => 'Semerkant',
                'Asia/Seoul' => 'Seul',
                'Asia/Singapore' => 'Singapur',
                'Asia/Srednekolymsk' => 'Srednekolymsk',
                'Asia/Taipei' => 'Taipei',
                'Asia/Tashkent' => 'Taşkent',
                'Asia/Tehran' => 'Tehran',
                'Asia/Thimphu' => 'Thimphu',
                'Asia/Tbilisi' => 'Tiflis',
                'Asia/Tokyo' => 'Tokyo',
                'Asia/Tomsk' => 'Tomsk',
                'Asia/Ulaanbaatar' => 'Ulaanbaatar',
                'Asia/Urumqi' => 'Urumqi',
                'Asia/Ust-Nera' => 'Ust-Nera',
                'Asia/Vientiane' => 'Vientiane',
                'Asia/Vladivostok' => 'Vladivostok',
                'Asia/Yakutsk' => 'Yakutsk',
                'Asia/Yangon' => 'Yangon',
                'Asia/Yekaterinburg' => 'Yekaterinburg',
                'Asia/Yerevan' => 'Yerevan',
                'Asia/Damascus' => 'Şam',
                'Asia/Shanghai' => 'Şangay'
            ],
            'Atlantik' => [
                'Atlantic/Azores' => 'Azores',
                'Atlantic/Bermuda' => 'Bermuda',
                'Atlantic/Faroe' => 'Faroe Adaları',
                'Atlantic/South_Georgia' => 'Güney Georgia',
                'Atlantic/Canary' => 'Kanarya',
                'Atlantic/Madeira' => 'Madeira',
                'Atlantic/Reykjavik' => 'Reykjavik',
                'Atlantic/Stanley' => 'Stanley',
                'Atlantic/St_Helena' => 'St Helena',
                'Atlantic/Cape_Verde' => 'Yeşil Burun Adaları'
            ],
            'Avrupa' => [
                'Europe/Amsterdam' => 'Amsterdam',
                'Europe/Andorra' => 'Andorra',
                'Europe/Astrakhan' => 'Astrakhan',
                'Europe/Athens' => 'Atina',
                'Europe/Belgrade' => 'Belgrad',
                'Europe/Berlin' => 'Berlin',
                'Europe/Bratislava' => 'Bratislava',
                'Europe/Brussels' => 'Brüksel',
                'Europe/Budapest' => 'Budapeşte',
                'Europe/Busingen' => 'Busingen',
                'Europe/Bucharest' => 'Bükreş',
                'Europe/Dublin' => 'Dublin',
                'Europe/Gibraltar' => 'Gibraltar',
                'Europe/Guernsey' => 'Guernsey',
                'Europe/Helsinki' => 'Helsinki',
                'Europe/Istanbul' => 'İstanbul',
                'Europe/Jersey' => 'Jersey',
                'Europe/Kaliningrad' => 'Kaliningrad',
                'Europe/Kyiv' => 'Kiev',
                'Europe/Kirov' => 'Kirov',
                'Europe/Chisinau' => 'Kişinev',
                'Europe/Copenhagen' => 'Kopenhag',
                'Europe/Lisbon' => 'Lizbon',
                'Europe/Ljubljana' => 'Ljubljana',
                'Europe/London' => 'Londra',
                'Europe/Luxembourg' => 'Lüksemburg',
                'Europe/Madrid' => 'Madrid',
                'Europe/Malta' => 'Malta',
                'Europe/Isle_of_Man' => 'Man adası',
                'Europe/Mariehamn' => 'Mariehamn',
                'Europe/Minsk' => 'Minsk',
                'Europe/Monaco' => 'Monako',
                'Europe/Moscow' => 'Moskova',
                'Europe/Oslo' => 'Oslo',
                'Europe/Paris' => 'Paris',
                'Europe/Podgorica' => 'Podgorica',
                'Europe/Prague' => 'Prag',
                'Europe/Riga' => 'Riga',
                'Europe/Rome' => 'Roma',
                'Europe/Samara' => 'Samara',
                'Europe/San_Marino' => 'San Marino',
                'Europe/Saratov' => 'Saratov',
                'Europe/Sarajevo' => 'Saraybosna',
                'Europe/Simferopol' => 'Simferopol',
                'Europe/Skopje' => 'Skopje',
                'Europe/Sofia' => 'Sofya',
                'Europe/Stockholm' => 'Stokholm',
                'Europe/Tallinn' => 'Tallinn',
                'Europe/Tirane' => 'Tirane',
                'Europe/Ulyanovsk' => 'Ulyanovsk',
                'Europe/Vaduz' => 'Vaduz',
                'Europe/Warsaw' => 'Varşova',
                'Europe/Vatican' => 'Vatikan',
                'Europe/Vilnius' => 'Vilnius',
                'Europe/Vienna' => 'Viyana',
                'Europe/Volgograd' => 'Volgograd',
                'Europe/Zagreb' => 'Zagreb',
                'Europe/Zurich' => 'Zürih',
            ],
            'Avustralya' => [
                'Australia/Adelaide' => 'Adelaide',
                'Australia/Brisbane' => 'Brisbane',
                'Australia/Broken_Hill' => 'Broken Hill',
                'Australia/Darwin' => 'Darwin',
                'Australia/Eucla' => 'Eucla',
                'Australia/Hobart' => 'Hobart',
                'Australia/Lindeman' => 'Lindeman',
                'Australia/Lord_Howe' => 'Lord Howe',
                'Australia/Melbourne' => 'Melbourne',
                'Australia/Perth' => 'Perth',
                'Australia/Sydney' => 'Sidney',
            ],
            'Hindistan' => [
                'Indian/Antananarivo' => 'Antananarivo',
                'Indian/Christmas' => 'Christmas',
                'Indian/Cocos' => 'Cocos',
                'Indian/Comoro' => 'Comoro',
                'Indian/Kerguelen' => 'Kerguelen',
                'Indian/Mahe' => 'Mahe',
                'Indian/Maldives' => 'Maldivler',
                'Indian/Mauritius' => 'Mauritius',
                'Indian/Mayotte' => 'Mayotte',
                'Indian/Reunion' => 'Reunion',
                'Indian/Chagos' => 'Çagos',
            ],
            'Pasifik' => [
                'Pacific/Apia' => 'Apia',
                'Pacific/Auckland' => 'Auckland',
                'Pacific/Bougainville' => 'Bougainville',
                'Pacific/Chatham' => 'Chatham',
                'Pacific/Chuuk' => 'Chuuk',
                'Pacific/Easter' => 'Easter',
                'Pacific/Efate' => 'Efate',
                'Pacific/Fakaofo' => 'Fakaofo',
                'Pacific/Fiji' => 'Fiji',
                'Pacific/Funafuti' => 'Funafuti',
                'Pacific/Galapagos' => 'Galapagos',
                'Pacific/Gambier' => 'Gambier',
                'Pacific/Guadalcanal' => 'Guadalcanal',
                'Pacific/Guam' => 'Guam',
                'Pacific/Honolulu' => 'Honolulu',
                'Pacific/Kanton' => 'Kanton',
                'Pacific/Kiritimati' => 'Kiritimati',
                'Pacific/Kosrae' => 'Kosrae',
                'Pacific/Kwajalein' => 'Kwajalein',
                'Pacific/Majuro' => 'Majuro',
                'Pacific/Marquesas' => 'Marquesas',
                'Pacific/Midway' => 'Midway',
                'Pacific/Nauru' => 'Nauru',
                'Pacific/Niue' => 'Niue',
                'Pacific/Norfolk' => 'Norfolk',
                'Pacific/Noumea' => 'Noumea',
                'Pacific/Pago_Pago' => 'Pago Pago',
                'Pacific/Palau' => 'Palau',
                'Pacific/Pitcairn' => 'Pitcairn',
                'Pacific/Pohnpei' => 'Pohnpei',
                'Pacific/Port_Moresby' => 'Port Moresby',
                'Pacific/Rarotonga' => 'Rarotonga',
                'Pacific/Saipan' => 'Saipan',
                'Pacific/Tahiti' => 'Tahiti',
                'Pacific/Tarawa' => 'Tarawa',
                'Pacific/Tongatapu' => 'Tongatapu',
                'Pacific/Wake' => 'Wake',
                'Pacific/Wallis' => 'Wallis',
            ],
            'UTC' => [
                'UTC' => 'UTC',
            ],
            'Manuel zaman farkları' => [
                'UTC-12' => 'UTC-12',
                'UTC-11.5' => 'UTC-11:30',
                'UTC-11' => 'UTC-11',
                'UTC-10.5' => 'UTC-10:30',
                'UTC-10' => 'UTC-10',
                'UTC-9.5' => 'UTC-9:30',
                'UTC-9' => 'UTC-9',
                'UTC-8.5' => 'UTC-8:30',
                'UTC-8' => 'UTC-8',
                'UTC-7.5' => 'UTC-7:30',
                'UTC-7' => 'UTC-7',
                'UTC-6.5' => 'UTC-6:30',
                'UTC-6' => 'UTC-6',
                'UTC-5.5' => 'UTC-5:30',
                'UTC-5' => 'UTC-5',
                'UTC-4.5' => 'UTC-4:30',
                'UTC-4' => 'UTC-4',
                'UTC-3.5' => 'UTC-3:30',
                'UTC-3' => 'UTC-3',
                'UTC-2.5' => 'UTC-2:30',
                'UTC-2' => 'UTC-2',
                'UTC-1.5' => 'UTC-1:30',
                'UTC-1' => 'UTC-1',
                'UTC-0.5' => 'UTC-0:30',
                'UTC+0' => 'UTC+0',
                'UTC+0.5' => 'UTC+0:30',
                'UTC+1' => 'UTC+1',
                'UTC+1.5' => 'UTC+1:30',
                'UTC+2' => 'UTC+2',
                'UTC+2.5' => 'UTC+2:30',
                'UTC+3' => 'UTC+3',
                'UTC+3.5' => 'UTC+3:30',
                'UTC+4' => 'UTC+4',
                'UTC+4.5' => 'UTC+4:30',
                'UTC+5' => 'UTC+5',
                'UTC+5.5' => 'UTC+5:30',
                'UTC+5.75' => 'UTC+5:45',
                'UTC+6' => 'UTC+6',
                'UTC+6.5' => 'UTC+6:30',
                'UTC+7' => 'UTC+7',
                'UTC+7.5' => 'UTC+7:30',
                'UTC+8' => 'UTC+8',
                'UTC+8.5' => 'UTC+8:30',
                'UTC+8.75' => 'UTC+8:45',
                'UTC+9' => 'UTC+9',
                'UTC+9.5' => 'UTC+9:30',
                'UTC+10' => 'UTC+10',
                'UTC+10.5' => 'UTC+10:30',
                'UTC+11' => 'UTC+11',
                'UTC+11.5' => 'UTC+11:30',
                'UTC+12' => 'UTC+12',
                'UTC+12.75' => 'UTC+12:45',
                'UTC+13' => 'UTC+13',
                'UTC+13.75' => 'UTC+13:45',
                'UTC+14' => 'UTC+14'
            ]
        ];
    }
}
